baseURL: "https://thnee.se/"
title: "thnee.se"

pygmentsUseClasses: true

markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    codeFences: true
    guessSyntax: false
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 4

menu:
  main:
    - name: "articles"
      url: "/"
      weight: 1
    - name: "tools"
      url: "/tools/"
      weight: 2
    - name: "about"
      url: "/about/"
      weight: 3

taxonomies:
  category: "categories"
  tag: "tags"

disableKinds: ["taxonomy", "taxonomyTerm"]
